package com.itech.membership

import enums.Role;

/**
 * SecRole
 * A domain class describes the data object and it's mapping to the database
 * Generated by spring-security-core plug-in
 */
class SecRole {

	String authority

	static mapping = {
		cache true
	}

	static constraints = {
		authority blank: false, unique: true, inList: ['ROLE_ADMIN', 'ROLE_DOCTOR', 'ROLE_RECEPTIONIST']
	}
}
